<?php
/**
 * ContactOperationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  AutoPilot\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
* AutoPilot API
 *
* Set of API that allow CRM to communicate with AutoPilotHQ
 *
* OpenAPI spec version: 0.0.3-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.0
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace AutoPilot\;

use {{invokerPackage}}\Configuration;
use {{invokerPackage}}\ApiException;
use {{invokerPackage}}\ObjectSerializer;

/**
 * ContactOperationApiTest Class Doc Comment
 *
 * @category Class
 * @package  AutoPilot\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ContactOperationApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createOrUpdateContact
     *
     * Create or update a contact.
     *
     */
    public function testCreateOrUpdateContact()
    {
    }

    /**
     * Test case for createOrUpdateContacts
     *
     * Create or update multiple contact.
     *
     */
    public function testCreateOrUpdateContacts()
    {
    }

    /**
     * Test case for deleteContact
     *
     * Delete a contact from AutoPilot.
     *
     */
    public function testDeleteContact()
    {
    }

    /**
     * Test case for getContactInfo
     *
     * Returns contact information from AutoPilot.
     *
     */
    public function testGetContactInfo()
    {
    }

    /**
     * Test case for getFirstContactSet
     *
     * Get first set of contacts present in AutoPilot.
     *
     */
    public function testGetFirstContactSet()
    {
    }

    /**
     * Test case for getNextContactSet
     *
     * Get next set of contacts present in AutoPilot.
     *
     */
    public function testGetNextContactSet()
    {
    }
}
