<?php
/**
 * HooksApiTest
 * PHP version 5
 *
 * @category Class
 * @package  AutoPilot\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
* AutoPilot API
 *
* Set of API that allow CRM to communicate with AutoPilotHQ
 *
* OpenAPI spec version: 0.0.3-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.0
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace AutoPilot\;

use {{invokerPackage}}\Configuration;
use {{invokerPackage}}\ApiException;
use {{invokerPackage}}\ObjectSerializer;

/**
 * HooksApiTest Class Doc Comment
 *
 * @category Class
 * @package  AutoPilot\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class HooksApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteHooks
     *
     * delete all hooks.
     *
     */
    public function testDeleteHooks()
    {
    }

    /**
     * Test case for getHooks
     *
     * get all list of all hooks present in AutoPilot.
     *
     */
    public function testGetHooks()
    {
    }

    /**
     * Test case for registerHooks
     *
     * register a hook.
     *
     */
    public function testRegisterHooks()
    {
    }

    /**
     * Test case for unregisterHook
     *
     * Unregister a hook.
     *
     */
    public function testUnregisterHook()
    {
    }
}
