<?php
/**
 * ListOperationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  AutoPilot\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
* AutoPilot API
 *
* Set of API that allow CRM to communicate with AutoPilotHQ
 *
* OpenAPI spec version: 0.0.3-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.0
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace AutoPilot\;

use {{invokerPackage}}\Configuration;
use {{invokerPackage}}\ApiException;
use {{invokerPackage}}\ObjectSerializer;

/**
 * ListOperationApiTest Class Doc Comment
 *
 * @category Class
 * @package  AutoPilot\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ListOperationApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addToList
     *
     * Add contact to list.
     *
     */
    public function testAddToList()
    {
    }

    /**
     * Test case for checkContactInList
     *
     * Check if contact is present in AutoPilot.
     *
     */
    public function testCheckContactInList()
    {
    }

    /**
     * Test case for getAllList
     *
     * Returns all list present in AutoPilot.
     *
     */
    public function testGetAllList()
    {
    }

    /**
     * Test case for getFirstContactSetInList
     *
     * Get first set of contacts present in a list from AutoPilot.
     *
     */
    public function testGetFirstContactSetInList()
    {
    }

    /**
     * Test case for getNextContactSetInList
     *
     * Get next set of contacts present in a list from AutoPilot.
     *
     */
    public function testGetNextContactSetInList()
    {
    }

    /**
     * Test case for removeFromList
     *
     * Remove a contact from a list in AutoPilot.
     *
     */
    public function testRemoveFromList()
    {
    }
}
