<?php
/**
 * AddContactTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  AutoPilot\
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
* AutoPilot API
 *
* Set of API that allow CRM to communicate with AutoPilotHQ
 *
* OpenAPI spec version: 0.0.3-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.0
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace AutoPilot\;

/**
 * AddContactTest Class Doc Comment
 *
 * @category    Class
 * @description AddContact
 * @package     AutoPilot\
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AddContactTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AddContact"
     */
    public function testAddContact()
    {
    }
}
